site_name: ML from Books
site_description: Learning Machine Learning and Finance through Code and Intuition
site_author: Simranjeet Singh
repo_url: https://github.com/simranjeetsinghwork/ml-from-books
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - toc.integrate
  palette:
    primary: blue
    accent: indigo
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - def_list
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - awesome-pages

nav:
  - Home: index.md
  - Regression:
      - Linear Regression: regression/linear_regression.md
      - Ridge and Lasso: regression/ridge_lasso.md
  - Classification:
      - Logistic Regression: classification/logistic_regression.md
  - Mathematical Finance:
      - Intro to Financial Markets and Bonds: finance/intro_to_financial_markets_and_bonds.md
      - Intro to Stocks, Futures & Forwards and Swaps: finance/intro_to_stocks_futures_forwards_and_swaps.md

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
